import VersoBlog
import AnalysisBook.Home
import AnalysisBook.LiterateModule
import Book -- This imports the sections. It's generated by the `genLib` job in the Lake config


open Verso Genre Blog Site Syntax

open Output Html Template Theme in
def theme : Theme := { Theme.default with
  primaryTemplate := do
    return {{
      <html>
        <head>
          <meta charset="UTF-8"/>
          <title>{{ (← param (α := String) "title") }} " — Verso "</title>
          <link rel="stylesheet" href="/static/style.css"/>
          <script>"window.__versoSiteRoot=\"/analysis/\""</script>
          {{← builtinHeader }}
        </head>
        <body>
          <header>
            <div class="inner-wrap">

            <nav class="top" role="navigation">
              <ol>
                <li><a href="/">"Home"</a></li>
                <li><a href="/docs/">"Documentation"</a></li>
                {{ ← dirLinks (← read).site }}
              </ol>
            </nav>
          </div>
          </header>
          <div class="main" role="main">
            <div class="wrap">
              {{ (← param "content") }}
            </div>
          </div>
        </body>
      </html>
    }}
  }
  |>.override #[] ⟨do return {{<div class="frontpage"><h1>{{← param "title"}}</h1> {{← param "content"}}</div>}}, id⟩


def demoSite : Site := site AnalysisBook.Home /
  static "static" ← "./static_files"
  "sec2e" Book.Analysis.Section_2_epilogue
  "sec21" Book.Analysis.Section_2_1
  "sec22" Book.Analysis.Section_2_2
  "sec23" Book.Analysis.Section_2_3
  "sec31" Book.Analysis.Section_3_1
  "sec41" Book.Analysis.Section_4_1
  "sec42" Book.Analysis.Section_4_2
  "sec43" Book.Analysis.Section_4_3
  "sec51" Book.Analysis.Section_5_1
  "sec52" Book.Analysis.Section_5_2
  "sec53" Book.Analysis.Section_5_3
  "sec54" Book.Analysis.Section_5_4
  "sec55" Book.Analysis.Section_5_5
  "sec5e" Book.Analysis.Section_5_epilogue
  "sec61" Book.Analysis.Section_6_1
  "sec62" Book.Analysis.Section_6_2
  "sec63" Book.Analysis.Section_6_3

def baseUrl := "https://teorth.github.io/analysis/docs/"

def linkTargets : Code.LinkTargets where
  const name := .some <| s!"{baseUrl}find?pattern={name}#doc"
  definition name := .some <| s!"{baseUrl}find?pattern={name}#doc"

def main := blogMain theme demoSite (linkTargets := linkTargets)
