import VersoBlog
import AnalysisBook.Home
import AnalysisBook.LiterateModule
import Book -- This imports the sections. It's generated by the `genLib` job in the Lake config


open Verso Genre Blog Site Syntax

open Output Html Template Theme in
def theme : Theme := { Theme.default with
  primaryTemplate := do
    return {{
      <html>
        <head>
          <meta charset="UTF-8"/>
          <title>{{ (← param (α := String) "title") }} " — Verso "</title>
          <link rel="stylesheet" href="/static/style.css"/>
          <script>"window.__versoSiteRoot=\"/analysis/\""</script>
          {{← builtinHeader }}
        </head>
        <body>
          <header>
            <div class="inner-wrap">

            <nav class="top" role="navigation">
              <ol>
                <li><a href="/">"Home"</a></li>
                <li><a href="/docs/">"Documentation"</a></li>
                {{ ← dirLinks (← read).site }}
              </ol>
            </nav>
          </div>
          </header>
          <div class="main" role="main">
            <div class="wrap">
              {{ (← param "content") }}
            </div>
          </div>
        </body>
      </html>
    }}
  }
  |>.override #[] ⟨do return {{<div class="frontpage"><h1>{{← param "title"}}</h1> {{← param "content"}}</div>}}, id⟩


def demoSite : Site := site AnalysisBook.Home /
  static "static" ← "./static_files"
  "sec21" Book.Analysis.Section_2_1
  "sec22" Book.Analysis.Section_2_2
  "sec23" Book.Analysis.Section_2_3
  "sec2e" Book.Analysis.Section_2_epilogue
  "sec31" Book.Analysis.Section_3_1
  "sec32" Book.Analysis.Section_3_2
  "sec33" Book.Analysis.Section_3_3
  "sec34" Book.Analysis.Section_3_4
  "sec35" Book.Analysis.Section_3_5
  "sec36" Book.Analysis.Section_3_6
  "sec3e" Book.Analysis.Section_3_epilogue
  "sec41" Book.Analysis.Section_4_1
  "sec42" Book.Analysis.Section_4_2
  "sec43" Book.Analysis.Section_4_3
  "sec44" Book.Analysis.Section_4_4
  "sec51" Book.Analysis.Section_5_1
  "sec52" Book.Analysis.Section_5_2
  "sec53" Book.Analysis.Section_5_3
  "sec54" Book.Analysis.Section_5_4
  "sec55" Book.Analysis.Section_5_5
  "sec56" Book.Analysis.Section_5_6
  "sec5e" Book.Analysis.Section_5_epilogue
  "sec61" Book.Analysis.Section_6_1
  "sec62" Book.Analysis.Section_6_2
  "sec63" Book.Analysis.Section_6_3
  "sec64" Book.Analysis.Section_6_4
  "sec65" Book.Analysis.Section_6_5
  "sec66" Book.Analysis.Section_6_6
  "sec67" Book.Analysis.Section_6_7
  "sec6e" Book.Analysis.Section_6_epilogue
  "sec71" Book.Analysis.Section_7_1
  "sec72" Book.Analysis.Section_7_2
  "sec73" Book.Analysis.Section_7_3
  "sec74" Book.Analysis.Section_7_4
  "sec75" Book.Analysis.Section_7_5
  "sec81" Book.Analysis.Section_8_1
  "sec82" Book.Analysis.Section_8_2
  "sec83" Book.Analysis.Section_8_3
  "sec84" Book.Analysis.Section_8_4
  "sec85" Book.Analysis.Section_8_5
  "sec91" Book.Analysis.Section_9_1
  "sec92" Book.Analysis.Section_9_2
  "sec93" Book.Analysis.Section_9_3
  "sec94" Book.Analysis.Section_9_4
  "sec95" Book.Analysis.Section_9_5
  "sec96" Book.Analysis.Section_9_6
  "sec97" Book.Analysis.Section_9_7
  "sec98" Book.Analysis.Section_9_8
  "sec99" Book.Analysis.Section_9_9
  "sec910" Book.Analysis.Section_9_10
  "sec101" Book.Analysis.Section_10_1
  "sec102" Book.Analysis.Section_10_2
  "sec103" Book.Analysis.Section_10_3
  "sec104" Book.Analysis.Section_10_4
  "sec105" Book.Analysis.Section_10_5
  "sec111" Book.Analysis.Section_11_1
  "sec112" Book.Analysis.Section_11_2
  "sec113" Book.Analysis.Section_11_3
  "sec114" Book.Analysis.Section_11_4
  "sec115" Book.Analysis.Section_11_5
  "sec116" Book.Analysis.Section_11_6
  "sec117" Book.Analysis.Section_11_7
  "sec118" Book.Analysis.Section_11_8
  "sec119" Book.Analysis.Section_11_9
  "sec1110" Book.Analysis.Section_11_10
  "appA1" Book.Analysis.Appendix_A_1
  "appA2" Book.Analysis.Appendix_A_2
  "appA3" Book.Analysis.Appendix_A_3
  "appA4" Book.Analysis.Appendix_A_4
  "appA5" Book.Analysis.Appendix_A_5
  "appA6" Book.Analysis.Appendix_A_6
  "appA7" Book.Analysis.Appendix_A_7
  "appB1" Book.Analysis.Appendix_B_1
  "appB2" Book.Analysis.Appendix_B_2

def baseUrl := "https://teorth.github.io/analysis/docs/"

def linkTargets : Code.LinkTargets α where
  const name _ := #[mkLink s!"{baseUrl}find?pattern={name}#doc"]
  definition name _ := #[mkLink s!"{baseUrl}find?pattern={name}#doc"]
where
  mkLink href := {shortDescription := "doc", description := "API documentation", href}

def main := blogMain theme demoSite (linkTargets := linkTargets)
